#pragma kernel TemporalUpscaling

Texture2DArray<float4>   _QuarterCloudBuffer;   // current frame's quarter-res raymarch
Texture2DArray<float4>   _HistoryBuffer;        // previous frame's full-res result (read)
RWTexture2DArray<float4> _CloudBuffer;          // current frame's full-res result (write)
Texture2DArray<float>    _CloudDepthTex;        // quarter-res encoded cloud depth
Texture2DArray<float>    _DepthTex;             // full-res scene depth
float4   _CameraPos[2];   
float4x4 _CurrInvViewProj[2]; // (P * V)^-1 for current frame
float4x4 _PrevViewProj[2];    // P * V for previous frame
float4x4 _CurrViewProj[2];
float2   _Resolution;
float2  _QuarterResolution;
float3  MovementOffset;
uint    _FrameIndex;
int _BigDivider;
float4  _ZBufferParams;
SamplerState    sampler_linear_clamp;
SamplerState    sampler_bilinear_clamp;
SamplerState    sampler_trilinear_clamp;
SamplerState    sampler_point_clamp;

float LinearEyeDepth(float d) {
    return 1.0 / (_ZBufferParams.z * d + _ZBufferParams.w);
}

float3 ReconstructWorldPos(float2 uv, float deviceDepth, uint eyeIndex) {
    float4 ndc = float4(uv * 2.0 - 1.0, deviceDepth, 1.0);
    float4 worldPos = mul(_CurrInvViewProj[eyeIndex], ndc);
    return worldPos.xyz / worldPos.w;
}
float3 GetRayDir(float2 uv, uint eyeIndex) {
    float2 ndcXY    = float2(uv.x, 1.0 - uv.y) * 2.0 - 1.0; 
    float4 ndc      = float4(ndcXY, 0.0, 1.0);               
    float4 worldFar = mul(_CurrInvViewProj[eyeIndex], ndc);
    return normalize(worldFar.xyz / worldFar.w - _CameraPos[eyeIndex].xyz);
}

[numthreads(8, 8, 1)]
void TemporalUpscaling(uint3 id : SV_DispatchThreadID) {
    if (id.x >= (uint)_Resolution.x || id.y >= (uint)_Resolution.y) return;

    float2 fullUV       = (float2(id.xy) + 0.5) / _Resolution;
    float frameOffset = _FrameIndex %(_BigDivider*_BigDivider);
    float2 jitter = float2(frameOffset % _BigDivider, frameOffset / _BigDivider);
    float2  quarterCoord = (id.xy-jitter) / _BigDivider;
    float2 quarterUV    = (float2(quarterCoord) + 0.5) / _QuarterResolution;

    float4 newSample      =  _QuarterCloudBuffer.SampleLevel(sampler_trilinear_clamp, float3(quarterUV, id.z), 0);
    float  cloudWorldDist  = _CloudDepthTex.SampleLevel(sampler_point_clamp,  float3(quarterUV, id.z), 0).r;

    if (cloudWorldDist < 0.1) {
        _CloudBuffer[id.xyz] = float4(0, 0, 0, 0);
        return;
    }

    _CloudBuffer[id.xyz] = newSample;
    return;
}