#pragma kernel Merge

Texture2DArray<float4>   _SrcTex;
RWTexture2DArray<float4> _OutputTex;
Texture2DArray<float4>   _CloudBuffer;
Texture2DArray<float>    _DepthTex;

float2 _Resolution;

int _FlipY;

[numthreads(8, 8, 1)]
void Merge(uint3 id : SV_DispatchThreadID) {
    if (id.x >= (uint)_Resolution.x ||
        id.y >= (uint)_Resolution.y)
    return;

    uint2 pixel = id.xy;
    uint2 ogPixel = uint2(pixel.x,  pixel.y);
    if (_FlipY == 0)
    pixel.y =  (_Resolution.y - 1 - pixel.y) ;

    float4 src = _SrcTex[uint3(ogPixel, id.z)];
    float4 cloud = _CloudBuffer[uint3(pixel, id.z)];
    float depth = _DepthTex[uint3(ogPixel, id.z)];
    float4 result = src;

    bool isSkyPixel = depth == 0;

    float alpha = saturate(cloud.a);
    alpha *= alpha;

    // Only blend clouds where valid and sky is visible
    if (alpha > 0.0001 && isSkyPixel) {
        result.rgb = lerp(src.rgb, cloud.rgb, alpha);
        result.a = 1.0;
    }

    _OutputTex[uint3(ogPixel, id.z)] = result;
}